# Generated by Django 4.2 on 2025-01-28 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_deliveryrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryrequest',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='deliveryrequest',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='deliveryrequest',
            name='status',
            field=models.CharField(choices=[('В обработке', 'В обработке'), ('В пути', 'В пути'), ('Доставлено', 'Доставлено')], default='В обработке', max_length=100),
        ),
    ]
