# Generated by Django 4.2 on 2025-01-26 06:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news_image'),
        ),
    ]
